# Generated by Django 5.1 on 2024-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
